# Configuração do Servidor Web
server.port=8080

# --- Configuração do Banco de Dados (PostgreSQL) ---
# A URL de conexão aponta para o banco 'dailytasks' que criamos no Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/dailytasks

# As credenciais DEVEM BATER com o docker-compose.yml
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuração do JPA (Hibernate) ---
# 'update': O Hibernate tentará criar/atualizar as tabelas com base nas suas classes.
# Perfeito para desenvolvimento.
spring.jpa.hibernate.ddl-auto=update

# Define explicitamente o "dialeto" do SQL para evitar erros de metadados
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opcional: Mostra o SQL gerado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chave secreta para assinatura dos tokens JWT
api.security.token.secret=minha-chave-secreta-super-dificil-12345